### ISSUE TITLE
Media Pipe Dataset Creation

### ISSUE THREAD

**Issue by Sonica-B** [Sonica-B/RoboFusion#1]
1. Data creation using media-pipe
[MediaPipe Docs]( https://ai.google.dev/edge/mediapipe/solutions/vision/hand_landmarker)

**Comment by AnkitGole007** [comment]
I have tried implementing the following features until now(Code pushed on Git - 18th Nov 2024):

1. Created a Holistic model that implements both Pose and Hand landmark detection 
2. Creating a skeleton for the entire arm(Shoulder and Elbow Landmarks from Pose Model and 21-Hand Landmarks from Hand model)
3. Retrieving 3D coordinates for all the landmarks and storing them in a CSV file
4. Currently working on storing the dynamic angles calculated between each possible triplet of landmarks

**Comment by AnkitGole007** [comment]
The Hand Landmark Detection model has been updated and pushed on GitHub:

1. Only using the Hand Landmark model as we are only working with hand gestures
2. Further the Sensor integration part will be done to get the Thetas of the entire arm and further integrated with the Gripper Robotic arm
3. Only changes will be made in app.py and MLModel/models
4. @shivamshinde123 and @HarshChhajed-3010 will further work on integrating the Computer Vision model and ROS2(Reference Link: https://chatgpt.com/share/673f9b70-e900-8001-96d8-b71c16b48f56)
