### ISSUE TITLE
Literature Review 

### ISSUE THREAD

**Issue by Sonica-B** [Sonica-B/RoboFusion#3]

**Comment by AnkitGole007** [comment]
[Proposal Document](https://docs.google.com/document/d/1-DEBmHzPao7i932bTEBhA-bW2jqC6aAs2HX4GH-Fa1w/edit?tab=t.0)

- Added MediaPipe references(Google Research Blog, Tensorflow)
- Summarized about MediaPipe in the Literature review section(1. 3D Hand Tracking and Gesture Recognition with MediaPipe)
- Added comments regarding merging content of multiple references

**Comment by Sonica-B** [comment]
Review completed 
[ML-Project Proposal.pdf](https://github.com/user-attachments/files/17672139/ML-Project.Proposal.pdf)
